from src.motion_model import get_system_matrices
print("random walk")
Fi, Q, H, R = get_system_matrices("random_walk", q=1, r=1, timestep = 1, to_numpy = False)
print(Fi)
print(Q)
print(H)
print(R)
print("nearly_constant_velocity")
Fi, Q, H, R = get_system_matrices("nearly_constant_velocity", q=1, r=1, timestep = 1, to_numpy = False)
print(Fi)
print(Q)
print(H)
print(R)
print("nearly_constant_acceleration")
Fi, Q, H, R = get_system_matrices("nearly_constant_acceleration", q=1, r=1, timestep = 1, to_numpy = False)
print(Fi)
print(Q)
print(H)
print(R)